# Generated by Django 3.0.3 on 2020-09-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Option4',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choice_Text', models.CharField(max_length=100)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer_Text', models.CharField(max_length=100)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
    ]
