# Generated by Django 3.0.3 on 2020-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200930_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
