# Generated by Django 3.0.3 on 2020-10-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200930_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='Question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='QuizID',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
