# Generated by Django 3.0.3 on 2020-10-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201001_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Question_Text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
