# Generated by Django 3.0.3 on 2020-10-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20201001_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Answer',
            field=models.CharField(max_length=100),
        ),
    ]
