# Generated by Django 3.0.3 on 2020-10-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20201001_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Answer',
            field=models.CharField(default='Answer', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option1',
            field=models.CharField(default='Option1', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option2',
            field=models.CharField(default='Option2', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option3',
            field=models.CharField(blank=True, default='Option3', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option4',
            field=models.CharField(blank=True, default='Option4', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_Text',
            field=models.CharField(default='Question', max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Description',
            field=models.CharField(default='QuizName', max_length=200),
        ),
    ]
