# Generated by Django 3.0.3 on 2020-10-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20201002_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Description',
            field=models.CharField(max_length=200),
        ),
    ]
