# Generated by Django 3.0.3 on 2020-10-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_quizscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Subject'),
        ),
    ]
