# Generated by Django 3.0.3 on 2020-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20201010_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Attendance_required',
            field=models.IntegerField(default=75, null=True),
        ),
    ]
