# Generated by Django 3.0.3 on 2020-10-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_quiz_starting_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizscore',
            old_name='Score',
            new_name='Marks_Obtained',
        ),
        migrations.AddField(
            model_name='quizscore',
            name='Max_Marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
